//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORSBusinessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public int applicationNo { get; set; }
        public Nullable<int> jobId { get; set; }
        public Nullable<int> jobSeekerId { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
