//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORSBusinessLayer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class JobSeeker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobSeeker()
        {
            this.Applicants = new HashSet<Applicant>();
        }
    
        public int jobSeekerId { get; set; }
        public Nullable<int> userId { get; set; }
        [MaxLength(40, ErrorMessage = "Field length should be less than 100")]
        public string address { get; set; }
        [Range(0,40, ErrorMessage ="Experience should be a valid number between 0 and 40")]
        public Nullable<int> experience { get; set; }
        public string qualification { get; set; }
        [MaxLength(40, ErrorMessage = "Field length should be less than 40")]
        public string profession { get; set; }
        [MaxLength(40, ErrorMessage = "Field length should be less than 40")]
        public string skillSet { get; set; }
        [MaxLength(40, ErrorMessage ="File name is too large")]
        public string resume { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applicant> Applicants { get; set; }
        public virtual User User { get; set; }
    }
}
